### ISSUE TITLE
build the image error?

### ISSUE THREAD

**Issue by zhangtianai** [flex-dapps/gantree-cli-docker#4]
```
Step 14/22 : RUN npm install -g gantree-cli@$GANTREE_CLI_VERSION
 ---> Running in abe70370a4fc
/usr/local/bin/gantree-cli -> /usr/local/lib/node_modules/gantree-cli/src/index.js

> storage-engine@3.0.7 postinstall /usr/local/lib/node_modules/gantree-cli/node_modules/storage-engine
> node ./compatibility/detect.js

internal/fs/utils.js:230
    throw err;
    ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/gantree-cli/node_modules/storage-engine/lib/compatibility/index.js'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1355:35)
    at /usr/local/lib/node_modules/gantree-cli/node_modules/storage-engine/lib/compatibility/detect.js:35:15
    at Object.<anonymous> (/usr/local/lib/node_modules/gantree-cli/node_modules/storage-engine/lib/compatibility/detect.js:45:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/gantree-cli/node_modules/storage-engine/lib/compatibility/index.js'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storage-engine@3.0.7 postinstall: `node ./compatibility/detect.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storage-engine@3.0.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-22T03_53_19_607Z-debug.log
```

**Comment by rozifus** [comment]
Thanks for reporting this @zhangtianai 

I've attempted to rebuild the image myself on a clean system and it seems to be working for me

Could you provide:
- Operating system name and version
- Docker version from `docker -v`
- The docker build command you're using 

And I'll see if I can reproduce this error
